// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package at.co.federmann.gtd.domain;

import at.co.federmann.gtd.domain.Goal;
import java.io.Serializable;

privileged aspect Goal_Roo_Serializable {
    
    declare parents: Goal implements Serializable;
    
    private static final long Goal.serialVersionUID = 1L;
    
}
