// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package at.co.federmann.gtd.domain;

import at.co.federmann.gtd.domain.GtdAction;
import java.io.Serializable;

privileged aspect GtdAction_Roo_Serializable {
    
    declare parents: GtdAction implements Serializable;
    
    private static final long GtdAction.serialVersionUID = 1L;
    
}
