// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package at.co.federmann.gtd.domain;

import at.co.federmann.gtd.domain.GtdAction;
import at.co.federmann.gtd.domain.GtdActionDataOnDemand;
import at.co.federmann.gtd.domain.GtdActionIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect GtdActionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: GtdActionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: GtdActionIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: GtdActionIntegrationTest: @Transactional;
    
    @Autowired
    GtdActionDataOnDemand GtdActionIntegrationTest.dod;
    
    @Test
    public void GtdActionIntegrationTest.testCountGtdActions() {
        Assert.assertNotNull("Data on demand for 'GtdAction' failed to initialize correctly", dod.getRandomGtdAction());
        long count = GtdAction.countGtdActions();
        Assert.assertTrue("Counter for 'GtdAction' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void GtdActionIntegrationTest.testFindGtdAction() {
        GtdAction obj = dod.getRandomGtdAction();
        Assert.assertNotNull("Data on demand for 'GtdAction' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GtdAction' failed to provide an identifier", id);
        obj = GtdAction.findGtdAction(id);
        Assert.assertNotNull("Find method for 'GtdAction' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'GtdAction' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void GtdActionIntegrationTest.testFindAllGtdActions() {
        Assert.assertNotNull("Data on demand for 'GtdAction' failed to initialize correctly", dod.getRandomGtdAction());
        long count = GtdAction.countGtdActions();
        Assert.assertTrue("Too expensive to perform a find all test for 'GtdAction', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<GtdAction> result = GtdAction.findAllGtdActions();
        Assert.assertNotNull("Find all method for 'GtdAction' illegally returned null", result);
        Assert.assertTrue("Find all method for 'GtdAction' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void GtdActionIntegrationTest.testFindGtdActionEntries() {
        Assert.assertNotNull("Data on demand for 'GtdAction' failed to initialize correctly", dod.getRandomGtdAction());
        long count = GtdAction.countGtdActions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<GtdAction> result = GtdAction.findGtdActionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'GtdAction' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'GtdAction' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void GtdActionIntegrationTest.testFlush() {
        GtdAction obj = dod.getRandomGtdAction();
        Assert.assertNotNull("Data on demand for 'GtdAction' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GtdAction' failed to provide an identifier", id);
        obj = GtdAction.findGtdAction(id);
        Assert.assertNotNull("Find method for 'GtdAction' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyGtdAction(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'GtdAction' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GtdActionIntegrationTest.testMergeUpdate() {
        GtdAction obj = dod.getRandomGtdAction();
        Assert.assertNotNull("Data on demand for 'GtdAction' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GtdAction' failed to provide an identifier", id);
        obj = GtdAction.findGtdAction(id);
        boolean modified =  dod.modifyGtdAction(obj);
        Integer currentVersion = obj.getVersion();
        GtdAction merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'GtdAction' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GtdActionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'GtdAction' failed to initialize correctly", dod.getRandomGtdAction());
        GtdAction obj = dod.getNewTransientGtdAction(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'GtdAction' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'GtdAction' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'GtdAction' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void GtdActionIntegrationTest.testRemove() {
        GtdAction obj = dod.getRandomGtdAction();
        Assert.assertNotNull("Data on demand for 'GtdAction' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GtdAction' failed to provide an identifier", id);
        obj = GtdAction.findGtdAction(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'GtdAction' with identifier '" + id + "'", GtdAction.findGtdAction(id));
    }
    
}
