// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package at.co.federmann.gtd.domain;

import at.co.federmann.gtd.domain.GtdAction;
import at.co.federmann.gtd.domain.GtdActionDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect GtdActionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: GtdActionDataOnDemand: @Component;
    
    private Random GtdActionDataOnDemand.rnd = new SecureRandom();
    
    private List<GtdAction> GtdActionDataOnDemand.data;
    
    public GtdAction GtdActionDataOnDemand.getNewTransientGtdAction(int index) {
        GtdAction obj = new GtdAction();
        setName(obj, index);
        return obj;
    }
    
    public void GtdActionDataOnDemand.setName(GtdAction obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public GtdAction GtdActionDataOnDemand.getSpecificGtdAction(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        GtdAction obj = data.get(index);
        Long id = obj.getId();
        return GtdAction.findGtdAction(id);
    }
    
    public GtdAction GtdActionDataOnDemand.getRandomGtdAction() {
        init();
        GtdAction obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return GtdAction.findGtdAction(id);
    }
    
    public boolean GtdActionDataOnDemand.modifyGtdAction(GtdAction obj) {
        return false;
    }
    
    public void GtdActionDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = GtdAction.findGtdActionEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'GtdAction' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<GtdAction>();
        for (int i = 0; i < 10; i++) {
            GtdAction obj = getNewTransientGtdAction(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
