// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package at.co.federmann.gtd.domain;

import at.co.federmann.gtd.domain.GtdActionIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect GtdActionIntegrationTest_Roo_Configurable {
    
    declare @type: GtdActionIntegrationTest: @Configurable;
    
}
